services:
  portfolio:
    image: portfolio:latest
    networks:
      - proxy
    build: ./code
    container_name: portfolio
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-http.rule=Host(`lucas-saillot.fr`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"
      - "traefik.http.routers.portfolio-https.rule=Host(`lucas-saillot.fr`)"
      - "traefik.http.routers.portfolio-https.entrypoints=websecure"
      - "traefik.http.routers.portfolio-https.tls=true"
      - "traefik.http.routers.portfolio-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"

networks:
  proxy:
    external: true