services:
  portfolio:
    image: portfolio:latest
    ports:
      - "8050:80"
    networks:
      - proxy
    build: ./code
    container_name: portfolio
    restart: unless-stopped

networks:
  proxy:
    external: true